name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
  schedule:
    - cron: '41 21 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        # LTS versions
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-
      - name: Initialize CodeQL
        if: ${{ matrix.java == '17' }}
        uses: github/codeql-action/init@v1
        with:
          languages: java
      - name: Build with Gradle
        run: |
          if [ "${{ matrix.java == '8' }}" = "true" ]; then
              # the spotless jvm args dont work in 8
              rm gradle.properties
          fi;
          ./gradlew build -s
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        if: ${{ matrix.java == '17' }}
      - name: Perform CodeQL Analysis
        if: ${{ matrix.java == '17' }}
        uses: github/codeql-action/analyze@v1
      - name: Save reports
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: reports-${{ matrix.java }}
          path: build/reports/
