name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # LTS versions
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Cache Gradle wrapper
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-
      - name: Build with Gradle
        run: |
          if [ "${{ matrix.java == '8' }}" = "true" ]; then
              # the spotless jvm args dont work in 8
              rm gradle.properties
          fi;
          ./gradlew build installDist -s
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        if: ${{ matrix.java == '17' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: yuzawa-san
         password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/yuzawa-san/googolplex-theater
      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ matrix.java == '17' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Save reports
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: reports-${{ matrix.java }}
          path: build/reports/
