name: Snyk Monitor

on:
  workflow_dispatch:
  schedule:
    - cron:  '21 12 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - uses: snyk/actions/setup@master
      - name: Snyk monitor 
        run: snyk monitor --all-projects -d --org=yuzawa-san --configuration-matching='^runtimeClasspath' --remote-repo-url='https://github.com/yuzawa-san/googolplex-theater/'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
